---

- name: Playbook 6
  hosts: all
  become: yes

  tasks:
    - name: install Apache2
      apt: name=apache2 state=latest 
      when: ansible_distribution == "Ubuntu"

    - name: install Nginx
      apt: name={{to_install}} state=latest
      when: to_install is defined  
    
    - name: add .txt file
      file: name=/home/ansible/{{file}} state=touch
      when: file in file_list